name             'doxygen'
maintainer       'Michael Ferguson'
maintainer_email 'mpherg@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures doxygen from source'
long_description 'Installs/Configures doxygen from source'
version          '0.1.1'
recipe           'doxygen::source', 'Installs doxygen from source'
